export const BUSINESS_TYPES = {
  barbershop: {
    id: 'barbershop',
    name: 'Barbería',
    emoji: '✂️',
    description: 'Cortes, barba y estilo masculino',
    accentColor: '#00FF88',
    gradientTo: '#0A1A0F',
    staffLabel: 'Barbero',
    staffLabelPlural: 'Barberos',
    bookingTitle: '¿Qué te hacemos hoy?',
    stepLabels: ['Servicio', 'Barbero', 'Fecha y hora', 'Tus datos'],
    defaultServices: [
      { name: 'Corte de cabello', duration_minutes: 30, price: 25000, category: 'CORTES' },
      { name: 'Corte + barba', duration_minutes: 45, price: 35000, category: 'COMBOS' },
      { name: 'Afeitado clásico', duration_minutes: 30, price: 20000, category: 'BARBA' },
    ],
  },
  beauty_salon: {
    id: 'beauty_salon',
    name: 'Salón de Belleza',
    emoji: '💇‍♀️',
    description: 'Cortes, color, keratina y más',
    accentColor: '#FF6B9D',
    gradientTo: '#1A0812',
    staffLabel: 'Estilista',
    staffLabelPlural: 'Estilistas',
    bookingTitle: '¿Qué servicio deseas hoy?',
    stepLabels: ['Servicio', 'Estilista', 'Fecha y hora', 'Tus datos'],
    defaultServices: [
      { name: 'Corte de cabello', duration_minutes: 45, price: 35000, category: 'CORTES' },
      { name: 'Tintura', duration_minutes: 120, price: 80000, category: 'COLOR' },
      { name: 'Keratina', duration_minutes: 150, price: 120000, category: 'TRATAMIENTOS' },
    ],
  },
  nail_studio: {
    id: 'nail_studio',
    name: 'Nail Studio',
    emoji: '💅',
    description: 'Semipermanente, acrílicas y nail art',
    accentColor: '#C084FC',
    gradientTo: '#120820',
    staffLabel: 'Nail Artist',
    staffLabelPlural: 'Nail Artists',
    bookingTitle: '¿Qué diseño te ponemos hoy?',
    stepLabels: ['Servicio', 'Artista', 'Fecha y hora', 'Tus datos'],
    defaultServices: [
      { name: 'Semipermanente', duration_minutes: 60, price: 45000, category: 'SEMIPERMANENTE' },
      { name: 'Acrílicas', duration_minutes: 90, price: 70000, category: 'ACRÍLICAS' },
      { name: 'Manicure clásico', duration_minutes: 45, price: 25000, category: 'CLÁSICO' },
    ],
  },
  spa: {
    id: 'spa',
    name: 'Spa / Estética',
    emoji: '🧖‍♀️',
    description: 'Masajes, faciales y bienestar',
    accentColor: '#34D399',
    gradientTo: '#051410',
    staffLabel: 'Especialista',
    staffLabelPlural: 'Especialistas',
    bookingTitle: '¿Qué tratamiento deseas?',
    stepLabels: ['Tratamiento', 'Especialista', 'Fecha y hora', 'Tus datos'],
    defaultServices: [
      { name: 'Masaje relajante 60min', duration_minutes: 60, price: 90000, category: 'MASAJES' },
      { name: 'Limpieza facial', duration_minutes: 75, price: 75000, category: 'FACIAL' },
      { name: 'Depilación completa', duration_minutes: 60, price: 85000, category: 'DEPILACIÓN' },
    ],
  },
  tattoo: {
    id: 'tattoo',
    name: 'Tatuajes / Piercing',
    emoji: '🎨',
    description: 'Arte en piel, diseños únicos',
    accentColor: '#FB923C',
    gradientTo: '#1A0B00',
    staffLabel: 'Artista',
    staffLabelPlural: 'Artistas',
    bookingTitle: '¿Qué sesión agendamos?',
    stepLabels: ['Tipo', 'Artista', 'Fecha y hora', 'Tus datos'],
    defaultServices: [
      { name: 'Consultoría + diseño', duration_minutes: 60, price: 50000, category: 'DISEÑO' },
      { name: 'Tatuaje pequeño', duration_minutes: 120, price: 150000, category: 'TATUAJES' },
      { name: 'Piercing', duration_minutes: 30, price: 40000, category: 'PIERCING' },
    ],
  },
  marketing_agency: {
    id: 'marketing_agency',
    name: 'Agencia de Marketing',
    emoji: '📸',
    description: 'Contenido, reels, foto y video para tu marca',
    accentColor: '#60A5FA',
    gradientTo: '#030B18',
    staffLabel: 'Creator',
    staffLabelPlural: 'Creators',
    bookingTitle: '¿Qué sesión agendamos?',
    stepLabels: ['Servicio', 'Creator', 'Fecha y hora', 'Tus datos'],
    defaultServices: [
      { name: 'Sesión de reels', duration_minutes: 120, price: 250000, category: 'VIDEO' },
      { name: 'Fotografía de producto', duration_minutes: 90, price: 180000, category: 'FOTO' },
      { name: 'Pack mensual redes', duration_minutes: 240, price: 600000, category: 'PACKS' },
    ],
  },
}

export const BUSINESS_TYPE_LIST = Object.values(BUSINESS_TYPES)
